remote_theme: pages-themes/minimal@v0.2.0
plugins: 
- jekyll-remote-theme
title: Yijin Wang
description: 
Behavior, Cognition and Neuroscience  
PhD Candidate  
American University  
- [ORCID](https://orcid.org/0009-0000-0567-8521)  
- [ResearchGate](https://www.researchgate.net/profile/Yijin-Wang-16?ev=hdr_xprf&_sg=pLhTgiQvvGwz_erfN_fLg0fol2TeFJBCAWjJrULRdW3B-AY476t4ZZxSKwisAt3RP3xQiyyPORx0y5h2CP4-1QTG&_tp=eyJjb250ZXh0Ijp7ImZpcnN0UGFnZSI6InB1YmxpY2F0aW9uIiwicGFnZSI6ImhvbWUiLCJwcmV2aW91c1BhZ2UiOiJob21lIiwicG9zaXRpb24iOiJnbG9iYWxIZWFkZXIifX0)  
- [LinkedIn]  
- [Google Scholar](https://scholar.google.com/citations?user=4IjkddYAAAAJ&hl=en&oi=ao)  
- [NCBI]  
language: en
logo: /img/portfolio.jpg
