remote_theme: pages-themes/minimal@v0.2.0
plugins: 
- jekyll-remote-theme
title: Yijin Wang
description: 
Behavior, Cognition and Neuroscience  
PhD Candidate  
American University  
[ORCID](https://orcid.org/0009-0000-0567-8521)  
[ResearchGate](https://www.researchgate.net/profile/Yijin-Wang-16?ev=hdr_xprf)  
[LinkedIn](https://www.linkedin.com/in/yijin-wang-013163323/)  
[Google Scholar](https://scholar.google.com/citations?user=4IjkddYAAAAJ&hl=en&oi=ao)  
[NCBI](https://www.ncbi.nlm.nih.gov/myncbi/yijin.wang.3/bibliography/public/)  
language: en
logo: /img/portfolio.jpg
show_downloads: true
